theme: jekyll-theme-minimal
title: Eric Douglas Pastore's Home Page

description: This landing page showcases my work in data science, analytics, and machine learning. 
It includes project summaries, research insights, and GitHub repositories demonstrating data-driven problem solving, exploratory analysis, predictive modeling, and real-world applications. 
